VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "Name"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Property Get Application() As Application
End Property

Property Get Category() As String
End Property
Property Let Category()
End Property

Property Get CategoryLocal() As String
End Property
Property Let CategoryLocal()
End Property

Property Get Comment() As String
End Property
Property Let Comment()
End Property

Property Get Creator() As XlCreator
End Property

Property Get Index() As Long
End Property

Property Get MacroType() As XlXLMMacroType
End Property
Property Let MacroType()
End Property

Property Get Name() As String
End Property
Property Let Name()
End Property

Property Get NameLocal() As String
End Property
Property Let NameLocal()
End Property

Property Get Parent() As Object
End Property

Property Get RefersTo() As Variant
End Property
Property Let RefersTo()
End Property

Property Get RefersToLocal() As Variant
End Property
Property Let RefersToLocal()
End Property

Property Get RefersToR1C1() As Variant
End Property
Property Let RefersToR1C1()
End Property

Property Get RefersToR1C1Local() As Variant
End Property
Property Let RefersToR1C1Local()
End Property

Property Get RefersToRange() As Range
End Property

Property Get ShortcutKey() As String
End Property
Property Let ShortcutKey()
End Property

Property Get ValidWorkbookParameter() As Boolean
End Property

Property Get Value() As String
End Property
Property Let Value()
End Property

Property Get Visible() As Boolean
End Property
Property Let Visible()
End Property

Property Get WorkbookParameter() As Boolean
End Property
Property Let WorkbookParameter()
End Property

Sub Delete()
End Sub