VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "Addin"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Property Get Application() As Application
End Property

Property Get CLSID() As String
End Property

Property Get Creator() As XlCreator
End Property

Property Get FullName() As String
End Property

Property Get Installed() As Boolean
End Property
Property Let Installed()
End Property

Property Get IsOpen() As Boolean
End Property

Property Get Name() As String
End Property

Property Get Parent() As Object
End Property

Property Get Path() As String
End Property

Property Get progID() As String
End Property