VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "Ranges"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Property Get Application() As Application
End Property

Property Get Count() As Long
End Property

Property Get Creator() As XlCreator
End Property

Property Get Item(Index) As Range
End Property

Property Get Parent() As Worksheet
End Property