VERSION 1.0 CLASS
BEGIN
MultiUse = -1  'True
END
Attribute VB_Name = "QueryTable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Property Get AdjustColumnWidth() As Boolean
End Property
Property Let AdjustColumnWidth()
End Property

Property Get Application() As Application
End Property

Property Get BackgroundQuery() As Boolean
End Property
Property Let BackgroundQuery()
End Property

Sub CancelRefresh()
End Sub

Property Get CommandText() As Variant
End Property
Property Let CommandText()
End Property

Property Get CommandType() As XlCmdType
End Property
Property Let CommandType()
End Property

Property Get Connection() As Variant
End Property
Property Let Connection()
End Property

Property Get Creator() As XlCreator
End Property

Sub Delete()
End Sub

Property Get Destination() As Range
End Property

Property Get EditWebPage() As Variant
End Property
Property Let EditWebPage()
End Property

Property Get EnableEditing() As Boolean
End Property
Property Let EnableEditing()
End Property

Property Get EnableRefresh() As Boolean
End Property
Property Let EnableRefresh()
End Property

Property Get FetchedRowOverflow() As Boolean
End Property

Property Get FieldNames() As Boolean
End Property
Property Let FieldNames()
End Property

Property Get FillAdjacentFormulas() As Boolean
End Property
Property Let FillAdjacentFormulas()
End Property

Property Get ListObject() As ListObject
End Property

Property Get MaintainConnection() As Boolean
End Property
Property Let MaintainConnection()
End Property

Property Get Name() As String
End Property
Property Let Name()
End Property

Property Get Parameters() As Parameters
End Property

Property Get Parent() As Object
End Property

Property Get PostText() As String
End Property
Property Let PostText()
End Property

Property Get PreserveColumnInfo() As Boolean
End Property
Property Let PreserveColumnInfo()
End Property

Property Get PreserveFormatting() As Boolean
End Property
Property Let PreserveFormatting()
End Property

Property Get QueryType() As XlQueryType
End Property

Property Get Recordset() As Object
End Property
Property Let Recordset()
End Property

Function Refresh(Optional BackgroundQuery) As Boolean
End Function

Property Get Refreshing() As Boolean
End Property

Property Get RefreshOnFileOpen() As Boolean
End Property
Property Let RefreshOnFileOpen()
End Property

Property Get RefreshPeriod() As Long
End Property
Property Let RefreshPeriod()
End Property

Property Get RefreshStyle() As XlCellInsertionMode
End Property
Property Let RefreshStyle()
End Property

Property Get RefreshStyle() As XlCellInsertionMode
End Property

Property Get ResultRange() As Range
End Property

Property Get RobustConnect() As XlRobustConnect
End Property
Property Let RobustConnect()
End Property

Property Get RowNumbers() As Boolean
End Property
Property Let RowNumbers()
End Property

Sub SaveAsODC(ODCFileName As String, Optional Description, Optional Keywords)
End Sub

Property Get SaveData() As Boolean
End Property
Property Let SaveData()
End Property

Property Get SavePassword() As Boolean
End Property
Property Let SavePassword()
End Property

Property Get Sort() As Sort
End Property

Property Get SourceConnectionFile() As String
End Property
Property Let SourceConnectionFile()
End Property

Property Get SourceDataFile() As String
End Property
Property Let SourceDataFile()
End Property

Property Get TextFileColumnDataTypes() As Variant
End Property
Property Let TextFileColumnDataTypes()
End Property

Property Get TextFileCommaDelimiter() As Boolean
End Property
Property Let TextFileCommaDelimiter()
End Property

Property Get TextFileDecimalSeparator() As String
End Property
Property Let TextFileDecimalSeparator()
End Property

Property Get TextFileFixedColumnWidths() As Variant
End Property
Property Let TextFileFixedColumnWidths()
End Property

Property Get TextFileOtherDelimiter() As String
End Property
Property Let TextFileOtherDelimiter()
End Property

Property Get TextFileParseType() As XlTextParsingType
End Property
Property Let TextFileParseType()
End Property

Property Get TextFilePlatform() As Long
End Property
Property Let TextFilePlatform()
End Property

Property Get TextFilePromptOnRefresh() As Boolean
End Property
Property Let TextFilePromptOnRefresh()
End Property

Property Get TextFileSemicolonDelimiter() As Boolean
End Property
Property Let TextFileSemicolonDelimiter()
End Property

Property Get TextFileSpaceDelimiter() As Boolean
End Property
Property Let TextFileSpaceDelimiter()
End Property

Property Get TextFileStartRow() As Long
End Property
Property Let TextFileStartRow()
End Property

Property Get TextFileTabDelimiter() As Boolean
End Property
Property Let TextFileTabDelimiter()
End Property

Property Get TextFileTextQualifier() As XlTextQualifier
End Property
Property Let TextFileTextQualifier()
End Property

Property Get TextFileThousandsSeparator() As String
End Property
Property Let TextFileThousandsSeparator()
End Property

Property Get TextFileTrailingMinusNumbers() As Boolean
End Property
Property Let TextFileTrailingMinusNumbers()
End Property

Property Get TextFileVisualLayout() As XlTextVisualLayoutType
End Property
Property Let TextFileVisualLayout()
End Property

Property Get WebConsecutiveDelimitersAsOne() As Boolean
End Property
Property Let WebConsecutiveDelimitersAsOne()
End Property

Property Get WebDisableDateRecognition() As Boolean
End Property
Property Let WebDisableDateRecognition()
End Property

Property Get WebDisableRedirections() As Boolean
End Property
Property Let WebDisableRedirections()
End Property

Property Get WebFormatting() As XlWebFormatting
End Property
Property Let WebFormatting()
End Property

Property Get WebPreFormattedTextToColumns() As Boolean
End Property
Property Let WebPreFormattedTextToColumns()
End Property

Property Get WebSelectionType() As XlWebSelectionType
End Property
Property Let WebSelectionType()
End Property

Property Get WebSingleBlockTextImport() As Boolean
End Property
Property Let WebSingleBlockTextImport()
End Property

Property Get WebTables() As String
End Property
Property Let WebTables()
End Property

Property Get WorkbookConnection() As WorkbookConnection
End Property